Milestone 3 : validations and model specs
Chrissiku/Rails-Blog pull request #3
Opened 2022-09-16 07:49 UTC by Chrissiku

## What I did ♻️ 
> In this project;s milesotne I add validations to my models and create specs for them.

## Project requirements 🟢 
- Add the following validations:
  - For the User model:
    - Name must not be blank.
    - PostsCounter must be an integer greater than or equal to zero.
  - For the Post model:
    - Title must not be blank.
    - Title must not exceed 250 characters.
    - CommentsCounter must be an integer greater than or equal to zero.
    - LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.

2022-09-16 08:08 UTC, danmainah requested changes
Hi @Chrissiku , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Github flow was correctly used


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-16 08:08 UTC, danmainah commented on spec/models/comment_spec.rb
> +RSpec.describe Comment, type: :model do
- [ ] Kindly check on your comment model I got the error below when running the test:
![image](https://user-images.githubusercontent.com/61408860/190588721-fc4c9e69-496f-45aa-8f8d-ce45e211c33b.png)

2022-09-16 08:08 UTC, danmainah commented on spec/models/like_spec.rb
> +RSpec.describe Like, type: :model do
- [ ] Kindy check on your like model, I encountered the error below when running the tests:
![image](https://user-images.githubusercontent.com/61408860/190589038-e5d73b7d-8abb-4025-96f5-7ac8adf208d8.png)

2022-09-16 08:08 UTC, danmainah commented on spec/models/post_spec.rb
> +RSpec.describe Post, type: :model do
- [ ] Kindy check your post model, I encountered this error when running the tests:
![image](https://user-images.githubusercontent.com/61408860/190589255-cd6d07ad-ac52-40bc-bfc0-4753312993d9.png)

2022-09-16 17:53 UTC, rotimiazeez requested changes
Hi @Chrissiku 👍🏽, 
Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Suggested changes
_Check the comments under the review._
## There seem to be an error in your migration file, kindly fix it
![Screenshot from 2022-09-16 18-48-29](https://user-images.githubusercontent.com/44624138/190701939-a73b186d-24a5-4408-bae0-28f4d44a6ac1.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-17 12:56 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @Chrissiku 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ You have written model specs
✔️ No linter errors

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 13:01 UTC, Chrissiku commented
Thank you @codepantha

2022-09-17 13:02 UTC, merged